# Generated by Django 2.2.10 on 2020-11-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos_poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('t', 'text'), ('o', 'choose one'), ('f', 'choose few')], default='text', max_length=50),
        ),
    ]
